@startuml 画面遷延図

[*] -> トップページ
トップページ --> 新規登録 
新規登録 --> トップページ

トップページ --> ログイン
ログイン --> トップページ

トップページ --> カード作成
カード作成 --> トップページ

トップページ --> カード
カード --> トップページ

state カード {
カード --> 問題1
問題1 -left-> 解答1 :正答
解答1 --> 問題2
問題2 -right-> 解答2 :誤答
解答2 --> 問題3
問題3 -left-> 解答3 :正答
解答3 --> トップページ
問題2再 -right-> 解答2再 :正答
}

@enduml
